apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-classifier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-classifier
  template:
    metadata:
      labels:
        app: image-classifier
    spec:
      containers:
      - name: image-classifier
        image: tuusuario/image-classifier
        ports:
        - containerPort: 5000